version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: instapic
    environment:
      POSTGRES_DB: instapic
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: